apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-phi-tiny-moe-test
  labels:
    app: vllm
    model: phi-tiny-moe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
      model: phi-tiny-moe-test
  template:
    metadata:
      labels:
        app: vllm
        model: phi-tiny-moe-test
    spec:
      # Temporarily remove runtimeClassName to test volume mount
      # runtimeClassName: nvidia
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        args:
        - --model
        - /models/Phi-tiny-MoE-instruct
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        - --tensor-parallel-size
        - "1"
        - --gpu-memory-utilization
        - "0.9"
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          # Temporarily remove GPU requirement to test volume
          limits:
            memory: 32Gi
          requests:
            memory: 16Gi
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
      volumes:
      - name: models
        hostPath:
          path: /models
          type: Directory
